[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda", "playwright-core"]

[functions.check-tennis]
  timeout = 30

[[redirects]]
  from = "/api/status"
  to = "/status"
  status = 200

[[redirects]]
  from = "/api/check"
  to = "/check"
  status = 200

[[redirects]]
  from = "/api/telegram"
  to = "/telegram"
  status = 200
